# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v5.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 488)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_62 = QtWidgets.QVBoxLayout()
        self.verticalLayout_62.setObjectName("verticalLayout_62")
        self.gridLayout.addLayout(self.verticalLayout_62, 21, 21, 1, 1)
        self.verticalLayout_60 = QtWidgets.QVBoxLayout()
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.camera_icon = QtWidgets.QPushButton(self.centralwidget)
        self.camera_icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/camOFFF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../icons/camONN.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.camera_icon.setIcon(icon)
        self.camera_icon.setIconSize(QtCore.QSize(40, 50))
        self.camera_icon.setObjectName("camera_icon")
        self.verticalLayout_60.addWidget(self.camera_icon)
        self.gridLayout.addLayout(self.verticalLayout_60, 22, 5, 1, 4)
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.gridLayout.addLayout(self.verticalLayout_49, 11, 0, 1, 1)
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.gridLayout.addLayout(self.verticalLayout_50, 1, 0, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.gridLayout.addLayout(self.verticalLayout_14, 21, 33, 1, 1)
        self.verticalLayout_84 = QtWidgets.QVBoxLayout()
        self.verticalLayout_84.setObjectName("verticalLayout_84")
        self.change_lens_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_lens_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/LENS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_lens_button.setIcon(icon1)
        self.change_lens_button.setIconSize(QtCore.QSize(40, 50))
        self.change_lens_button.setObjectName("change_lens_button")
        self.verticalLayout_84.addWidget(self.change_lens_button)
        self.gridLayout.addLayout(self.verticalLayout_84, 22, 1, 1, 4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout.addLayout(self.verticalLayout_6, 21, 48, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout.addLayout(self.verticalLayout_11, 21, 1, 1, 1)
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.gridLayout.addLayout(self.verticalLayout_42, 15, 0, 1, 1)
        self.verticalLayout_82 = QtWidgets.QVBoxLayout()
        self.verticalLayout_82.setObjectName("verticalLayout_82")
        self.gridLayout.addLayout(self.verticalLayout_82, 21, 6, 1, 1)
        self.verticalLayout_61 = QtWidgets.QVBoxLayout()
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.gridLayout.addLayout(self.verticalLayout_61, 21, 5, 1, 1)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.gridLayout.addLayout(self.verticalLayout_33, 21, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.updown_slider = QtWidgets.QSlider(self.centralwidget)
        self.updown_slider.setStyleSheet("background: #565e7c;")
        self.updown_slider.setOrientation(QtCore.Qt.Vertical)
        self.updown_slider.setObjectName("updown_slider")
        self.horizontalLayout_5.addWidget(self.updown_slider)
        self.gridLayout.addLayout(self.horizontalLayout_5, 19, 0, 2, 1)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.gridLayout.addLayout(self.verticalLayout_19, 21, 38, 1, 1)
        self.verticalLayout_65 = QtWidgets.QVBoxLayout()
        self.verticalLayout_65.setObjectName("verticalLayout_65")
        self.gridLayout.addLayout(self.verticalLayout_65, 21, 19, 1, 1)
        self.verticalLayout_77 = QtWidgets.QVBoxLayout()
        self.verticalLayout_77.setObjectName("verticalLayout_77")
        self.gridLayout.addLayout(self.verticalLayout_77, 21, 15, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addLayout(self.verticalLayout_2, 21, 31, 1, 1)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.gridLayout.addLayout(self.verticalLayout_24, 21, 43, 1, 1)
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.gridLayout.addLayout(self.verticalLayout_47, 12, 0, 1, 1)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.gridLayout.addLayout(self.verticalLayout_27, 21, 49, 1, 1)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.gridLayout.addLayout(self.verticalLayout_26, 16, 0, 1, 1)
        self.verticalLayout_71 = QtWidgets.QVBoxLayout()
        self.verticalLayout_71.setObjectName("verticalLayout_71")
        self.gridLayout.addLayout(self.verticalLayout_71, 21, 3, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout.addLayout(self.verticalLayout_8, 21, 30, 1, 1)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.gridLayout.addLayout(self.verticalLayout_43, 14, 0, 1, 1)
        self.verticalLayout_81 = QtWidgets.QVBoxLayout()
        self.verticalLayout_81.setObjectName("verticalLayout_81")
        self.gridLayout.addLayout(self.verticalLayout_81, 21, 13, 1, 1)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.gridLayout.addLayout(self.verticalLayout_34, 21, 26, 1, 1)
        self.verticalLayout_78 = QtWidgets.QVBoxLayout()
        self.verticalLayout_78.setObjectName("verticalLayout_78")
        self.gridLayout.addLayout(self.verticalLayout_78, 21, 10, 1, 1)
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.gridLayout.addLayout(self.verticalLayout_41, 10, 0, 1, 1)
        self.verticalLayout_57 = QtWidgets.QVBoxLayout()
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.gridLayout.addLayout(self.verticalLayout_57, 5, 0, 1, 1)
        self.verticalLayout_59 = QtWidgets.QVBoxLayout()
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.gridLayout.addLayout(self.verticalLayout_59, 8, 0, 1, 1)
        self.verticalLayout_79 = QtWidgets.QVBoxLayout()
        self.verticalLayout_79.setObjectName("verticalLayout_79")
        self.gridLayout.addLayout(self.verticalLayout_79, 21, 7, 1, 1)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.gridLayout.addLayout(self.verticalLayout_23, 21, 42, 1, 1)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.gridLayout.addLayout(self.verticalLayout_20, 21, 39, 1, 1)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.gridLayout.addLayout(self.verticalLayout_22, 21, 41, 1, 1)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.gridLayout.addLayout(self.verticalLayout_30, 21, 24, 1, 1)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.gridLayout.addLayout(self.verticalLayout_36, 21, 23, 1, 1)
        self.verticalLayout_68 = QtWidgets.QVBoxLayout()
        self.verticalLayout_68.setObjectName("verticalLayout_68")
        self.gridLayout.addLayout(self.verticalLayout_68, 21, 12, 1, 1)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.gridLayout.addLayout(self.verticalLayout_39, 17, 0, 1, 1)
        self.verticalLayout_86 = QtWidgets.QVBoxLayout()
        self.verticalLayout_86.setObjectName("verticalLayout_86")
        self.right_button = QtWidgets.QPushButton(self.centralwidget)
        self.right_button.setText("")
        self.right_button.setObjectName("right_button")
        self.verticalLayout_86.addWidget(self.right_button)
        self.gridLayout.addLayout(self.verticalLayout_86, 22, 49, 1, 1)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.gridLayout.addLayout(self.verticalLayout_31, 21, 27, 1, 1)
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.gridLayout.addLayout(self.verticalLayout_44, 18, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout.addLayout(self.verticalLayout_12, 21, 32, 1, 1)
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.gridLayout.addLayout(self.verticalLayout_48, 13, 0, 1, 1)
        self.verticalLayout_76 = QtWidgets.QVBoxLayout()
        self.verticalLayout_76.setObjectName("verticalLayout_76")
        self.gridLayout.addLayout(self.verticalLayout_76, 21, 18, 1, 1)
        self.verticalLayout_72 = QtWidgets.QVBoxLayout()
        self.verticalLayout_72.setObjectName("verticalLayout_72")
        self.gridLayout.addLayout(self.verticalLayout_72, 22, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.gridLayout.addLayout(self.verticalLayout_16, 21, 36, 1, 1)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.gridLayout.addLayout(self.verticalLayout_29, 21, 29, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout.addLayout(self.verticalLayout_7, 21, 28, 1, 1)
        self.verticalLayout_69 = QtWidgets.QVBoxLayout()
        self.verticalLayout_69.setObjectName("verticalLayout_69")
        self.gridLayout.addLayout(self.verticalLayout_69, 21, 17, 1, 1)
        self.verticalLayout_64 = QtWidgets.QVBoxLayout()
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.gridLayout.addLayout(self.verticalLayout_64, 21, 16, 1, 1)
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.gridLayout.addLayout(self.verticalLayout_52, 9, 0, 1, 1)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.gridLayout.addLayout(self.verticalLayout_37, 3, 0, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout.addLayout(self.verticalLayout_13, 21, 34, 1, 1)
        self.verticalLayout_80 = QtWidgets.QVBoxLayout()
        self.verticalLayout_80.setObjectName("verticalLayout_80")
        self.gridLayout.addLayout(self.verticalLayout_80, 21, 9, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gridLayout.addLayout(self.verticalLayout_15, 21, 35, 1, 1)
        self.verticalLayout_67 = QtWidgets.QVBoxLayout()
        self.verticalLayout_67.setObjectName("verticalLayout_67")
        self.gridLayout.addLayout(self.verticalLayout_67, 21, 20, 1, 1)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.gridLayout.addLayout(self.verticalLayout_51, 4, 0, 1, 1)
        self.verticalLayout_66 = QtWidgets.QVBoxLayout()
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.gridLayout.addLayout(self.verticalLayout_66, 21, 4, 1, 1)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.gridLayout.addLayout(self.verticalLayout_21, 21, 40, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout.addLayout(self.horizontalLayout_3, 21, 0, 1, 1)
        self.verticalLayout_56 = QtWidgets.QVBoxLayout()
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.gridLayout.addLayout(self.verticalLayout_56, 2, 0, 1, 1)
        self.verticalLayout_83 = QtWidgets.QVBoxLayout()
        self.verticalLayout_83.setObjectName("verticalLayout_83")
        self.gridLayout.addLayout(self.verticalLayout_83, 21, 11, 1, 1)
        self.verticalLayout_55 = QtWidgets.QVBoxLayout()
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.gridLayout.addLayout(self.verticalLayout_55, 6, 0, 1, 1)
        self.verticalLayout_63 = QtWidgets.QVBoxLayout()
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        self.gridLayout.addLayout(self.verticalLayout_63, 21, 22, 1, 1)
        self.verticalLayout_54 = QtWidgets.QVBoxLayout()
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.gridLayout.addLayout(self.verticalLayout_54, 7, 0, 1, 1)
        self.verticalLayout_75 = QtWidgets.QVBoxLayout()
        self.verticalLayout_75.setObjectName("verticalLayout_75")
        self.gridLayout.addLayout(self.verticalLayout_75, 21, 14, 1, 1)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.gridLayout.addLayout(self.verticalLayout_17, 21, 37, 1, 1)
        self.verticalLayout_70 = QtWidgets.QVBoxLayout()
        self.verticalLayout_70.setObjectName("verticalLayout_70")
        self.gridLayout.addLayout(self.verticalLayout_70, 21, 8, 1, 1)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.gridLayout.addLayout(self.verticalLayout_35, 21, 25, 1, 1)
        self.verticalLayout_87 = QtWidgets.QVBoxLayout()
        self.verticalLayout_87.setObjectName("verticalLayout_87")
        self.video_icon = QtWidgets.QPushButton(self.centralwidget)
        self.video_icon.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/VIDOFF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("../icons/VIDON.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.video_icon.setIcon(icon2)
        self.video_icon.setIconSize(QtCore.QSize(40, 50))
        self.video_icon.setObjectName("video_icon")
        self.verticalLayout_87.addWidget(self.video_icon)
        self.gridLayout.addLayout(self.verticalLayout_87, 22, 9, 1, 4)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout.addLayout(self.verticalLayout_10, 21, 47, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout.addLayout(self.verticalLayout_5, 21, 44, 1, 1)
        self.verticalLayout_85 = QtWidgets.QVBoxLayout()
        self.verticalLayout_85.setObjectName("verticalLayout_85")
        self.forward_button = QtWidgets.QPushButton(self.centralwidget)
        self.forward_button.setText("")
        self.forward_button.setObjectName("forward_button")
        self.verticalLayout_85.addWidget(self.forward_button)
        self.backward_button = QtWidgets.QPushButton(self.centralwidget)
        self.backward_button.setText("")
        self.backward_button.setObjectName("backward_button")
        self.verticalLayout_85.addWidget(self.backward_button)
        self.gridLayout.addLayout(self.verticalLayout_85, 22, 48, 1, 1)
        self.verticalLayout_58 = QtWidgets.QVBoxLayout()
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.left_button = QtWidgets.QPushButton(self.centralwidget)
        self.left_button.setText("")
        self.left_button.setObjectName("left_button")
        self.verticalLayout_58.addWidget(self.left_button)
        self.gridLayout.addLayout(self.verticalLayout_58, 22, 47, 1, 1)
        self.verticalLayout_90 = QtWidgets.QVBoxLayout()
        self.verticalLayout_90.setObjectName("verticalLayout_90")
        self.show_video = QtWidgets.QPushButton(self.centralwidget)
        self.show_video.setText("")
        self.show_video.setObjectName("show_video")
        self.verticalLayout_90.addWidget(self.show_video)
        self.gridLayout.addLayout(self.verticalLayout_90, 14, 49, 6, 1)
        self.verticalLayout_89 = QtWidgets.QVBoxLayout()
        self.verticalLayout_89.setObjectName("verticalLayout_89")
        self.show_image = QtWidgets.QPushButton(self.centralwidget)
        self.show_image.setText("")
        self.show_image.setObjectName("show_image")
        self.verticalLayout_89.addWidget(self.show_image)
        self.gridLayout.addLayout(self.verticalLayout_89, 14, 48, 6, 1)
        self.verticalLayout_88 = QtWidgets.QVBoxLayout()
        self.verticalLayout_88.setObjectName("verticalLayout_88")
        self.turn_off = QtWidgets.QPushButton(self.centralwidget)
        self.turn_off.setText("")
        self.turn_off.setObjectName("turn_off")
        self.verticalLayout_88.addWidget(self.turn_off)
        self.gridLayout.addLayout(self.verticalLayout_88, 0, 48, 6, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.zoom_slider = QtWidgets.QSlider(self.centralwidget)
        self.zoom_slider.setStyleSheet("background: #565e7c;")
        self.zoom_slider.setOrientation(QtCore.Qt.Vertical)
        self.zoom_slider.setObjectName("zoom_slider")
        self.horizontalLayout_6.addWidget(self.zoom_slider)
        self.gridLayout.addLayout(self.horizontalLayout_6, 20, 48, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.brightness_slider = QtWidgets.QSlider(self.centralwidget)
        self.brightness_slider.setStyleSheet("background: #565e7c;")
        self.brightness_slider.setOrientation(QtCore.Qt.Vertical)
        self.brightness_slider.setObjectName("brightness_slider")
        self.horizontalLayout_2.addWidget(self.brightness_slider)
        self.gridLayout.addLayout(self.horizontalLayout_2, 20, 49, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_label = QtWidgets.QLabel(self.centralwidget)
        self.frame_label.setObjectName("frame_label")
        self.horizontalLayout.addWidget(self.frame_label)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 21, 47)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 22))
        self.menubar.setObjectName("menubar")
        self.menu_menu = QtWidgets.QMenu(self.menubar)
        self.menu_menu.setObjectName("menu_menu")
        self.connected_devices_menu = QtWidgets.QMenu(self.menubar)
        self.connected_devices_menu.setObjectName("connected_devices_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect_to_HDMI = QtWidgets.QAction(MainWindow)
        self.actionConnect_to_HDMI.setObjectName("actionConnect_to_HDMI")
        self.actionLibrary = QtWidgets.QAction(MainWindow)
        self.actionLibrary.setObjectName("actionLibrary")
        self.actionTurn_OFF = QtWidgets.QAction(MainWindow)
        self.actionTurn_OFF.setObjectName("actionTurn_OFF")
        self.action_connect_hdmi = QtWidgets.QAction(MainWindow)
        self.action_connect_hdmi.setObjectName("action_connect_hdmi")
        self.actionLibrary_2 = QtWidgets.QAction(MainWindow)
        self.actionLibrary_2.setObjectName("actionLibrary_2")
        self.actionTurn_OFF_2 = QtWidgets.QAction(MainWindow)
        self.actionTurn_OFF_2.setObjectName("actionTurn_OFF_2")
        self.actionSet_Preferences = QtWidgets.QAction(MainWindow)
        self.actionSet_Preferences.setObjectName("actionSet_Preferences")
        self.action_preferences = QtWidgets.QAction(MainWindow)
        self.action_preferences.setObjectName("action_preferences")
        self.menu_menu.addAction(self.action_connect_hdmi)
        self.menu_menu.addAction(self.action_preferences)
        self.menubar.addAction(self.menu_menu.menuAction())
        self.menubar.addAction(self.connected_devices_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.frame_label.setText(_translate("MainWindow", "TextLabel"))
        self.menu_menu.setTitle(_translate("MainWindow", "Menu"))
        self.connected_devices_menu.setTitle(_translate("MainWindow", "Connected Devices"))
        self.actionConnect_to_HDMI.setText(_translate("MainWindow", "Connect to HDMI"))
        self.actionLibrary.setText(_translate("MainWindow", "Library"))
        self.actionTurn_OFF.setText(_translate("MainWindow", "Turn OFF"))
        self.action_connect_hdmi.setText(_translate("MainWindow", "Connect to HDMI"))
        self.actionLibrary_2.setText(_translate("MainWindow", "Library"))
        self.actionTurn_OFF_2.setText(_translate("MainWindow", "Turn OFF"))
        self.actionSet_Preferences.setText(_translate("MainWindow", "Set Preferences"))
        self.action_preferences.setText(_translate("MainWindow", "Preferences"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

