# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'automi_ui_v3.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addLayout(self.horizontalLayout, 25, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.gridLayout.addLayout(self.horizontalLayout_15, 19, 0, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.gridLayout.addLayout(self.horizontalLayout_26, 21, 0, 1, 1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gridLayout.addLayout(self.verticalLayout_15, 29, 0, 1, 1)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.gridLayout.addLayout(self.verticalLayout_19, 29, 14, 1, 1)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.frame_label = QtWidgets.QLabel(self.centralwidget)
        self.frame_label.setText("")
        self.frame_label.setObjectName("frame_label")
        self.verticalLayout_35.addWidget(self.frame_label)
        self.gridLayout.addLayout(self.verticalLayout_35, 0, 2, 29, 30)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.gridLayout.addLayout(self.verticalLayout_39, 29, 24, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.gridLayout.addLayout(self.horizontalLayout_16, 18, 0, 1, 1)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.gridLayout.addLayout(self.horizontalLayout_37, 5, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.gridLayout.addLayout(self.horizontalLayout_13, 10, 0, 1, 1)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.gridLayout.addLayout(self.horizontalLayout_34, 12, 0, 1, 1)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.gridLayout.addLayout(self.verticalLayout_30, 29, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout.addLayout(self.horizontalLayout_10, 27, 0, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout.addLayout(self.verticalLayout_13, 29, 26, 1, 1)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.gridLayout.addLayout(self.verticalLayout_24, 29, 18, 1, 1)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.gridLayout.addLayout(self.horizontalLayout_29, 20, 0, 1, 1)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.gridLayout.addLayout(self.horizontalLayout_35, 9, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout.addLayout(self.verticalLayout_3, 29, 12, 1, 1)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.gridLayout.addLayout(self.horizontalLayout_36, 8, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.gridLayout.addLayout(self.horizontalLayout_17, 15, 0, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.gridLayout.addLayout(self.horizontalLayout_22, 2, 0, 1, 1)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.gridLayout.addLayout(self.verticalLayout_51, 4, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.gridLayout.addLayout(self.horizontalLayout_18, 14, 0, 1, 1)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.gridLayout.addLayout(self.horizontalLayout_33, 13, 0, 1, 1)
        self.verticalLayout_58 = QtWidgets.QVBoxLayout()
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.change_lens_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_lens_button.setObjectName("change_lens_button")
        self.verticalLayout_58.addWidget(self.change_lens_button)
        self.gridLayout.addLayout(self.verticalLayout_58, 29, 2, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.gridLayout.addLayout(self.horizontalLayout_21, 1, 0, 1, 1)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.gridLayout.addLayout(self.verticalLayout_20, 29, 16, 1, 1)
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.gridLayout.addLayout(self.verticalLayout_45, 29, 13, 1, 1)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.gridLayout.addLayout(self.horizontalLayout_30, 17, 0, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.gridLayout.addLayout(self.horizontalLayout_25, 16, 0, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.gridLayout.addLayout(self.horizontalLayout_27, 23, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.gridLayout.addLayout(self.horizontalLayout_24, 11, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gridLayout.addLayout(self.horizontalLayout_14, 24, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.video_icon = QtWidgets.QPushButton(self.centralwidget)
        self.video_icon.setObjectName("video_icon")
        self.verticalLayout_9.addWidget(self.video_icon)
        self.gridLayout.addLayout(self.verticalLayout_9, 29, 22, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout.addLayout(self.horizontalLayout_9, 26, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.gridLayout.addLayout(self.horizontalLayout_23, 6, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.gridLayout.addLayout(self.horizontalLayout_20, 0, 0, 1, 1)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.gridLayout.addLayout(self.horizontalLayout_31, 7, 0, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.gridLayout.addLayout(self.verticalLayout_16, 29, 10, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.gridLayout.addLayout(self.horizontalLayout_12, 28, 0, 1, 1)
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.gridLayout.addLayout(self.verticalLayout_50, 3, 0, 1, 1)
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.gridLayout.addLayout(self.verticalLayout_53, 29, 23, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout.addLayout(self.verticalLayout_12, 29, 27, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 29, 25, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout.addLayout(self.verticalLayout_11, 29, 19, 1, 1)
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.gridLayout.addLayout(self.verticalLayout_47, 29, 9, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.gridLayout.addLayout(self.horizontalLayout_28, 22, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout.addLayout(self.verticalLayout_7, 29, 4, 1, 1)
        self.verticalLayout_59 = QtWidgets.QVBoxLayout()
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.gridLayout.addLayout(self.verticalLayout_59, 29, 32, 1, 1)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.gridLayout.addLayout(self.verticalLayout_22, 29, 21, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.gridLayout.addLayout(self.verticalLayout_14, 29, 20, 1, 1)
        self.verticalLayout_55 = QtWidgets.QVBoxLayout()
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.left_button = QtWidgets.QPushButton(self.centralwidget)
        self.left_button.setObjectName("left_button")
        self.verticalLayout_55.addWidget(self.left_button)
        self.gridLayout.addLayout(self.verticalLayout_55, 29, 29, 1, 1)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.gridLayout.addLayout(self.verticalLayout_17, 29, 5, 1, 1)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.gridLayout.addLayout(self.verticalLayout_21, 29, 17, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout.addLayout(self.verticalLayout_6, 29, 28, 1, 1)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.gridLayout.addLayout(self.verticalLayout_23, 29, 8, 1, 1)
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.gridLayout.addLayout(self.verticalLayout_44, 29, 15, 1, 1)
        self.verticalLayout_60 = QtWidgets.QVBoxLayout()
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.gridLayout.addLayout(self.verticalLayout_60, 29, 3, 1, 1)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.camera_icon = QtWidgets.QPushButton(self.centralwidget)
        self.camera_icon.setObjectName("camera_icon")
        self.verticalLayout_43.addWidget(self.camera_icon)
        self.gridLayout.addLayout(self.verticalLayout_43, 29, 11, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout.addLayout(self.verticalLayout_8, 29, 7, 1, 1)
        self.verticalLayout_57 = QtWidgets.QVBoxLayout()
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.right_button = QtWidgets.QPushButton(self.centralwidget)
        self.right_button.setObjectName("right_button")
        self.verticalLayout_57.addWidget(self.right_button)
        self.gridLayout.addLayout(self.verticalLayout_57, 29, 31, 1, 1)
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.forward_button = QtWidgets.QPushButton(self.centralwidget)
        self.forward_button.setObjectName("forward_button")
        self.verticalLayout_52.addWidget(self.forward_button)
        self.backward_button = QtWidgets.QPushButton(self.centralwidget)
        self.backward_button.setObjectName("backward_button")
        self.verticalLayout_52.addWidget(self.backward_button)
        self.gridLayout.addLayout(self.verticalLayout_52, 29, 30, 1, 1)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.gridLayout.addLayout(self.verticalLayout_25, 29, 6, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.brightness_slider = QtWidgets.QSlider(self.centralwidget)
        self.brightness_slider.setOrientation(QtCore.Qt.Vertical)
        self.brightness_slider.setObjectName("brightness_slider")
        self.horizontalLayout_2.addWidget(self.brightness_slider)
        self.gridLayout.addLayout(self.horizontalLayout_2, 12, 1, 17, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.zoom_slider = QtWidgets.QSlider(self.centralwidget)
        self.zoom_slider.setOrientation(QtCore.Qt.Vertical)
        self.zoom_slider.setObjectName("zoom_slider")
        self.horizontalLayout_4.addWidget(self.zoom_slider)
        self.gridLayout.addLayout(self.horizontalLayout_4, 12, 32, 17, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.connected_devices_menu = QtWidgets.QMenu(self.menubar)
        self.connected_devices_menu.setObjectName("connected_devices_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect_to_HDMI = QtWidgets.QAction(MainWindow)
        self.actionConnect_to_HDMI.setObjectName("actionConnect_to_HDMI")
        self.actionLibrary = QtWidgets.QAction(MainWindow)
        self.actionLibrary.setObjectName("actionLibrary")
        self.actionTurn_OFF = QtWidgets.QAction(MainWindow)
        self.actionTurn_OFF.setObjectName("actionTurn_OFF")
        self.menuMenu.addAction(self.actionConnect_to_HDMI)
        self.menuMenu.addAction(self.actionLibrary)
        self.menuMenu.addAction(self.actionTurn_OFF)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.connected_devices_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.change_lens_button.setText(_translate("MainWindow", "Change Lens"))
        self.video_icon.setText(_translate("MainWindow", "Record"))
        self.left_button.setText(_translate("MainWindow", "Left"))
        self.camera_icon.setText(_translate("MainWindow", "Capture"))
        self.right_button.setText(_translate("MainWindow", "Right"))
        self.forward_button.setText(_translate("MainWindow", "Forward"))
        self.backward_button.setText(_translate("MainWindow", "Backward"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.connected_devices_menu.setTitle(_translate("MainWindow", "Connected Devices"))
        self.actionConnect_to_HDMI.setText(_translate("MainWindow", "Connect to HDMI"))
        self.actionLibrary.setText(_translate("MainWindow", "Library"))
        self.actionTurn_OFF.setText(_translate("MainWindow", "Turn OFF"))

